name: Proxy Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

# Убираем предупреждение Гитхаба, принудительно включая новый движок
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Используем последние версии экшенов (v4 и v5)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run checker
        run: python checker.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data.json
          
          # Если изменений в прокси нет, робот просто закончит работу без ошибки
          git commit -m "Update proxies: $(date)" || exit 0
          
          # СИЛОВОЙ ПРИЕМ: сначала впитываем твои правки с сайта, потом ставим свои
          git pull --rebase origin main
          git push origin main
