name: Proxy Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run checker
        run: python checker.py

      - name: Commit and Push (The Tank Method)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 1. Прячем наш новый файл во временную папку
          mv data.json /tmp/data.json
          
          # 2. Сбрасываем состояние репозитория до того, что сейчас на сервере Гитхаба
          git fetch origin main
          git reset --hard origin/main
          
          # 3. Возвращаем наш новый файл на место
          mv /tmp/data.json data.json
          
          # 4. Сохраняем и выталкиваем в сеть
          git add data.json
          git commit -m "Update proxies: $(date)" || exit 0
          git push origin main
